#!/bin/bash

# Use operators on variables

num1=10
num2=5

num3=$((num1+num2))
num4=$((num1-num2))
num5=$((num1*num2))
num6=$((num1/num2))

echo "$num1 + $num2 = $num3"
echo "$num1 - $num2 = $num4"
echo "$num1 * $num2 = $num5"
echo "$num1 / $num2 = $num6"
